const COLORS = {
    green: '#5cb85c',
    blue: '#337ab7',
    info: '#5bc0de',
    warning: '#f0ad4e',
    red: '#d9534f',
    untagged: '#ccc',
    orange: '#FFA500',
};

const TAGS = {
    algorithms: {title: 'algorithms', color: COLORS.blue},
    greedy: {title: 'greedy', colors: COLORS.blue},
    dp: {title: 'dynprog', colors: COLORS.blue},
    daq: {title: 'dividenconquer', colors: COLORS.blue},
    cool: {title: 'cool', color: COLORS.blue},
    awesome: {title: 'awesome', color: COLORS.green},
    another: {title: 'another', color: COLORS.red},
    graphs: {title: 'graphs', color: COLORS.green},
    proofs: {title: 'discretemath', color: COLORS.orange},
    combinatorics: {title: 'combinatorics', color: COLORS.red},
    optimality: {title: 'optimality', color: COLORS.red},
    probability: {title: 'probability', color: COLORS.red},
    recursion: {title: 'recursion', color: COLORS.red},
};

const items = [
    {title: 'Antimagic square', id: 'antimagic-square', tags: [TAGS.proofs]},
    {title: 'Antivirus system', id: 'antivirus-system', tags: [TAGS.graphs, TAGS.algorithms]},
    {title: 'Arthur\'s books', id: 'arthurs-books', tags: [TAGS.proofs, TAGS.algorithms]},
    {title: 'Balanced graphs', id: 'balanced-graphs', tags: [TAGS.graphs, TAGS.proofs]},
    {title: 'Balls in boxes', id: 'balls-in-boxes', tags: [TAGS.proofs, TAGS.algorithms, TAGS.greedy]},
    {title: 'Bridges', id: 'bridges', tags: [TAGS.graphs, TAGS.algorithms]},
    {title: 'Chessboard tiling', id: 'chessboard-tiling', tags: [TAGS.proofs]},
    {title: 'Cut the figure', id: 'cut-the-figure', tags: [TAGS.proofs]},
    {title: 'Find the number 2', id: 'find-number-2', tags: [TAGS.proofs]},
    {title: 'Find the number', id: 'find-number', tags: [TAGS.proofs]},
    {title: 'Florin coins', id: 'florin-coins', tags: [TAGS.proofs, TAGS.optimality]},
    {title: 'Game of Fifteen', id: '15-game', tags: [TAGS.proofs]},
    {title: 'Graph cliques', id: 'graph-cliques', tags: [TAGS.graphs, TAGS.algorithms]},
    {title: 'Guarinis puzzle', id: 'guarinis-puzzle', tags: [TAGS.graphs, TAGS.algorithms]},
    {title: 'Hamiltonian cycle', id: 'hamiltonian-cycle', tags: [TAGS.graphs, TAGS.algorithms]},
    {title: 'Hanoi towers', id: 'hanoi-towers', tags: [TAGS.proofs, TAGS.algorithms, TAGS.recursion]},
    {title: 'Job assignment', id: 'job-assignment', tags: [TAGS.graphs, TAGS.algorithms]},
    {title: 'Magic square', id: 'magic-square', tags: [TAGS.proofs]},
    {title: 'Make a tree', id: 'make-a-tree', tags: [TAGS.graphs, TAGS.algorithms]},
    {title: 'Map coloring', id: 'map-coloring', tags: [TAGS.graphs, TAGS.algorithms]},
    {title: 'N bishops', id: 'n-bishops', tags: [TAGS.proofs, TAGS.optimality]},
    {title: 'N diagonals', id: 'n-diagonals', tags: [TAGS.proofs, TAGS.optimality, TAGS.algorithms, TAGS.recursion]},
    {title: 'N knights', id: 'n-knights', tags: [TAGS.proofs, TAGS.optimality]},
    {title: 'N queens', id: 'n-queens', tags: [TAGS.proofs, TAGS.optimality]},
    {title: 'N rooks', id: 'n-rooks', tags: [TAGS.proofs, TAGS.optimality]},
    {title: 'Number of paths', id: 'number-of-paths', tags: [TAGS.combinatorics, TAGS.algorithms, TAGS.dp]},
    {title: 'Numbers in boxes', id: 'numbers-in-boxes', tags: [TAGS.proofs]},
    {title: 'Numbers on chessboard', id: 'numbers-on-chessboard', tags: [TAGS.proofs]},
    {title: 'Largest concatenate problem', id: 'largest-number', tags: [TAGS.greedy, TAGS.algorithms]},
    {title: 'Local maximum', id: 'local-maximum', tags: [TAGS.daq, TAGS.algorithms]},
    {title: 'Opposite colors', id: 'opposite-colors', tags: [TAGS.proofs, TAGS.algorithms, TAGS.daq, TAGS.recursion]},
    {title: 'Piece on chessboard', id: 'piece-on-chessboard', tags: [TAGS.proofs]},
    {title: 'Prime', id: 'prime', tags: [TAGS.proofs]},
    {title: 'Primitive calculator', id: 'primitive-calculator', tags: [TAGS.combinatorics, TAGS.algorithms, TAGS.dp]},
    {title: 'Prisoner and king', id: 'prisoner-and-king', tags: [TAGS.probability]},
    {title: 'Regular graph', id: 'regular-graph', tags: [TAGS.graphs]},
    {title: 'Road repair', id: 'road-repair', tags: [TAGS.graphs, TAGS.algorithms]},
    {title: 'Split weights', id: 'split-weights', tags: [TAGS.proofs]},
    {title: 'Subway lines', id: 'subway-lines', tags: [TAGS.graphs]},
    {title: 'Summing up binomials', id: 'summing-up-binomials', tags: [TAGS.combinatorics]},
    {title: 'Summing up digits', id: 'summing-up-digits', tags: [TAGS.proofs]},
    {title: 'Sums of rows and columns', id: 'sums-of-rows-and-columns', tags: [TAGS.proofs]},
    {title: 'Switching signs', id: 'switching-signs', tags: [TAGS.combinatorics]},
    {title: 'Take the last rock', id: 'take-the-last-rock', tags: [TAGS.proofs]},
    {title: 'Two rocks game', id: 'take-the-last-stone', tags: [TAGS.proofs, TAGS.algorithms, TAGS.dp]},
    {title: 'Three rocks game', id: 'three-rocks-game', tags: [TAGS.proofs, TAGS.algorithms, TAGS.dp]},
    {title: 'Three hotels', id: 'three-hotels', tags: [TAGS.proofs]},
    {title: 'Tossing coins', id: 'tossing-coins', tags: [TAGS.probability]},
    {title: 'Twice numbers', id: 'twice-numbers', tags: [TAGS.proofs, TAGS.optimality]},
    {title: 'Touch all segments', id: 'touch-all-segments', tags: [TAGS.algorithms, TAGS.greedy]},
    {title: 'Activity selection', id: 'activity-selection', tags: [TAGS.algorithms, TAGS.greedy]},
    {title: '21 questions game', id: 'clock-game', tags: [TAGS.algorithms, TAGS.daq, TAGS.recursion]},
    {title: 'Plow Truck', id: 'plow-truck', tags: [TAGS.graphs, TAGS.optimality]},
    {title: 'Delivery Problem', id: 'delivery-problem', tags: [TAGS.graphs, TAGS.optimality]},
];

module.exports = {
    colors: COLORS,
    items: items
};
